/*
  ============================================================
  📚 LESSON 15: JAVASCRIPT VARIABLES & ARRAYS
  ============================================================
  const = a variable that CANNOT be reassigned
  let   = a variable that CAN be reassigned
  var   = old-style (avoid in modern JS)

  An ARRAY is an ordered list of items, written with [ ].
  Items are separated by commas.
  You access items by INDEX (position), starting at 0:
    WORDS[0]  → "about"
    WORDS[1]  → "above"
  ============================================================
*/

// The list of possible answer words (common 5-letter words)
const WORDS = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
  "alike", "alive", "alley", "allow", "alone", "along", "alter", "angel",
  "anger", "angle", "angry", "anime", "ankle", "annex", "antic", "anvil",
  "apple", "apply", "arena", "argue", "arise", "armor", "aroma", "arose",
  "array", "arrow", "aside", "asset", "atlas", "attic", "audio", "audit",
  "avoid", "awake", "award", "awful", "awoke", "axiom",
  "badge", "badly", "bagel", "baker", "basic", "basis", "batch", "beach",
  "beard", "beast", "began", "begin", "being", "below", "bench", "berry",
  "birth", "black", "blade", "blame", "bland", "blank", "blast", "blaze",
  "bleed", "bless", "blind", "bliss", "block", "blood", "bloom", "blown",
  "board", "bonus", "boost", "booth", "bound", "boxer", "braid", "brain",
  "brave", "bread", "break", "breed", "brick", "bride", "brief", "bring",
  "brisk", "broth", "brown", "brush", "built", "bunch", "burnt",
  "cabin", "camel", "candy", "cargo", "carry", "catch", "cause", "cedar",
  "chair", "chalk", "chaos", "charm", "chart", "chase", "cheap", "check",
  "cheek", "cheer", "chess", "chest", "chief", "child", "chill", "china",
  "chirp", "choir", "choke", "chord", "civic", "civil", "clamp", "clang",
  "clasp", "class", "clean", "clear", "clerk", "click", "cliff", "climb",
  "cling", "clock", "clone", "close", "cloth", "cloud", "clout", "clown",
  "coast", "cobra", "codec", "comet", "comic", "comma", "coral", "couch",
  "could", "count", "court", "cover", "craft", "crash", "crazy", "cream",
  "creek", "crest", "crime", "crisp", "cross", "crowd", "crown", "cruel",
  "crush", "crust", "curve", "cycle",
  "daily", "dance", "datum", "dealt", "debut", "decoy", "delay", "delta",
  "dense", "depot", "depth", "derby", "digit", "dirty", "disco", "dodge",
  "doing", "doubt", "dough", "draft", "drain", "drama", "drank", "drawl",
  "dream", "drove", "drown", "druid", "drunk", "dryer", "duchy", "dwell",
  "dwelt",
  "eager", "eagle", "early", "earth", "eight", "elbow", "elite", "email",
  "ember", "empty", "ended", "enemy", "enjoy", "enter", "entry", "equal",
  "error", "essay", "event", "every", "exact", "exist", "extra",
  "fable", "facet", "faint", "fairy", "faith", "false", "fancy", "fatal",
  "fault", "feast", "fence", "feral", "ferry", "fetch", "fever", "fewer",
  "field", "fiery", "fifth", "fifty", "fight", "final", "finch", "first",
  "fixed", "flame", "flash", "flask", "fleet", "flesh", "flick", "flint",
  "float", "flood", "floor", "flora", "flour", "focus", "foggy", "force",
  "forge", "forte", "forum", "found", "frail", "frame", "fraud", "fresh",
  "front", "frost", "fruit", "fungi", "funny",
  "gamma", "gauge", "geese", "ghost", "giant", "given", "gizmo", "glade",
  "gland", "glare", "glass", "gleam", "glide", "gloom", "gloss", "glove",
  "going", "grace", "grade", "grain", "grand", "grant", "grape", "grasp",
  "grass", "grave", "great", "greed", "green", "greet", "grief", "grill",
  "grind", "groan", "groin", "grope", "gross", "group", "grove", "grown",
  "guard", "guess", "guest", "guide", "guild", "guile", "guise", "gulch",
  "gyrate",
  "habit", "haven", "heart", "heavy", "herbs", "heron", "hilly", "hoist",
  "holly", "honor", "horse", "hotel", "hound", "house", "hover", "human",
  "humid", "humor", "hurry",
  "ideal", "image", "imply", "inbox", "index", "indie", "infer", "ingot",
  "inner", "input", "inter", "intro",
  "jaunt", "jewel", "joint", "joust", "juice", "juicy", "jumbo", "juror",
  "karma", "knack", "knave", "kneel", "knelt", "knife", "knock", "known",
  "label", "lance", "large", "laser", "later", "laugh", "layer", "leapt",
  "learn", "lease", "least", "leave", "ledge", "legal", "lemon", "level",
  "light", "limit", "liner", "lingo", "liver", "local", "lodge", "logic",
  "loose", "lorry", "lover", "lower", "loyal", "lucky", "lumen", "lunar",
  "lunch", "lusty",
  "magic", "major", "maker", "manor", "maple", "march", "match", "mayor",
  "media", "mercy", "merge", "merit", "metal", "might", "minor", "minus",
  "mirth", "model", "money", "month", "moral", "mossy", "motel", "motto",
  "mount", "mouse", "mouth", "movie", "muddy", "mulch", "music", "musky",
  "naive", "nerve", "never", "night", "noble", "noise", "north", "notch",
  "novel", "nurse",
  "ocean", "offer", "olive", "onset", "opera", "optic", "orbit", "order",
  "organ", "other", "outer", "oxide",
  "paint", "panel", "panic", "paper", "patch", "pause", "peace", "peach",
  "penny", "perch", "phase", "phone", "photo", "piano", "pitch", "pixel",
  "pizza", "place", "plain", "plane", "plant", "plate", "plaza", "plead",
  "plumb", "plume", "plump", "plunk", "plush", "point", "poker", "polar",
  "power", "prawn", "press", "price", "pride", "prime", "print", "prior",
  "prize", "probe", "prone", "proof", "prose", "proud", "prove", "prowl",
  "pulse", "pupil", "purse", "pygmy",
  "queen", "query", "quest", "queue", "quick", "quiet", "quota", "quote",
  "radar", "radio", "rainy", "rally", "range", "rapid", "ratio", "reach",
  "ready", "realm", "rebel", "rebus", "recap", "regal", "reign", "relax",
  "relay", "remix", "repay", "rider", "ridge", "rifle", "right", "risky",
  "river", "rivet", "rocky", "rouge", "rough", "round", "royal", "ruler",
  "runny", "rural", "rusty",
  "sadly", "saint", "salad", "sandy", "sauce", "scale", "scene", "scope",
  "score", "scout", "screw", "seize", "sense", "serve", "seven", "shade",
  "shaft", "shake", "shall", "shame", "shape", "share", "sharp", "shawl",
  "sheep", "sheer", "shelf", "shell", "shift", "shine", "shirt", "shock",
  "shoot", "shore", "short", "shout", "shove", "sight", "sigma", "since",
  "sixth", "skill", "slash", "slate", "slave", "sleek", "sleep", "sleet",
  "slept", "slide", "slope", "sloth", "smack", "small", "smart", "smash",
  "smell", "smile", "smoke", "snack", "snake", "snare", "sneak", "solve",
  "sorry", "south", "space", "spare", "spark", "speak", "spear", "speed",
  "spend", "spicy", "spike", "spine", "spite", "split", "spoke", "spoon",
  "sport", "spray", "squad", "stack", "staff", "stage", "stain", "stair",
  "stake", "stale", "stall", "stand", "stank", "stare", "start", "state",
  "stave", "steal", "steam", "steel", "steep", "steer", "stern", "stiff",
  "still", "stock", "stomp", "stone", "stood", "storm", "story", "stout",
  "stove", "strap", "straw", "stray", "strip", "strut", "stuck", "study",
  "style", "sugar", "suite", "sunny", "super", "surge", "swamp", "swear",
  "sweep", "sweet", "swift", "swirl", "swoop",
  "table", "talon", "taunt", "teach", "tense", "terra", "theme", "there",
  "thick", "thing", "think", "thorn", "those", "three", "threw", "throw",
  "thump", "tiger", "tight", "timer", "tired", "title", "today", "token",
  "total", "touch", "tough", "tower", "toxic", "track", "trade", "trail",
  "train", "trait", "tramp", "trash", "trend", "trial", "trick", "tried",
  "troop", "trout", "truce", "truck", "truly", "trump", "trust", "truth",
  "tweak", "twice", "twirl", "twist", "tying",
  "ultra", "under", "unify", "unity", "until", "upper", "upset", "urban",
  "vague", "valor", "valve", "video", "vigor", "viral", "visit", "visor",
  "vista", "vital", "vivid", "vocal", "voice",
  "waste", "watch", "water", "weary", "weave", "wedge", "weigh", "weird",
  "whale", "wheat", "wheel", "where", "which", "while", "white", "whole",
  "wider", "wield", "witch", "woman", "world", "worry", "worse", "worst",
  "worth", "would", "wound", "wrath", "wreck", "wrist", "write", "wrote",
  "yacht", "yield", "young", "youth", "zebra", "zesty", "zilch", "zippy",
  "zonal"
];

// A larger set of valid words the player is ALLOWED to guess
// (includes less common words that won't be answers)
const VALID_GUESSES = new Set([
  ...WORDS,
  // extra valid words that are acceptable guesses but won't be answers
  "aargh", "abbot", "abhor", "aback", "abbey", "abide", "abler", "abode",
  "afoot", "afoul", "agile", "aging", "agony", "agora", "aglow", "agogg",
  "amaze", "amend", "amino", "among", "ample", "ached", "oaken", "oater",
  "ebony", "icier", "icing", "idyll", "imbue", "impel", "oxide", "ochre",
  "oddly", "offal", "okapi", "onion", "opine", "ovary", "ovoid", "ovule",
  "untie", "uncut", "unwed", "unwit", "upend", "upshot", "utter",
  "snort", "sodden", "soften", "soggy", "squab", "squat", "squid",
  "knobs", "knoll", "koala", "knead"
]);
